// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class changemodelsstructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changemodelsstructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201910252211247_changemodelsstructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
